In [1]:
import numpy as np

## Write a function so that the columns of the output matrix are powers of the input vector.

In [2]:
X=np.array([4,8,9,10])
X

array([ 4,  8,  9, 10])

In [4]:
np.vander(X,3)

array([[ 16,   4,   1],
       [ 64,   8,   1],
       [ 81,   9,   1],
       [100,  10,   1]])

## Question: Write a function to find moving average in an array over a window: 

## Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

In [5]:
arr=np.array( [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150])
k=3
arr

array([  3,   5,   7,   2,   8,  10,  11,  65,  72,  81,  99, 100, 150])

In [12]:
for i in range(len(arr)-k+1):
    print(round(arr[i:i+k].mean(),2))

5.0
4.67
5.67
6.67
9.67
28.67
49.33
72.67
84.0
93.33
116.33
